### ISSUE TITLE
Connecting to SparkPool

### ISSUE THREAD

**Issue by raycekar** [Chainfire/UselethMiner#1]
Hi,  I am wanting to give your miner a try but am having trouble connecting it to the Sparkpool.

This is what I have been trying:
.\uselethminer.exe [walletAddress].[machineID]@eth-us.sparkpool.com:3333 -t 6,8,90 --flavor avx2_intel

seems to get stuck at "Listening on 127.0.0.1:3326"

I am on a school network so not sure if you know if using your proxy to get around the issue would help or not.

**Comment by Chainfire** [comment]
SparkPool works fine for me, so it's likely a network issue on your end.
