### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by jonny7737** [Chainfire/UselethMiner#14]
From the STATUS snapshot below, what is "s/a"?

[2022-01-24 11:55:28][STATUS] CPU[ 4148840 h/s :: 1035 s/a :: 518605 h/s/t :: 8 t :: 64 sz :: 31.65 GB/s ]  GPU[ 1567409 h/s :: 2740 s/a :: 64 sz :: 11.96 GB/s ]

Thanks.

**Comment by Chainfire** [comment]
Seconds per accept

An accept being a nonce share with the pool that it agrees is a valid hash at or above the difficulty threshold it has set.

That's an estimation based on hashrate and pool difficulty, that would hold true on average given both hashrate and pool difficulty are stable, and you monitor it for a sufficiently long time.
