### ISSUE TITLE
Question: Failover and difficulty

### ISSUE THREAD

**Issue by tryadelion** [Chainfire/UselethMiner#19]
every time i start it on windows, for ethermine, i see the next line:
[2022-02-08 21:54:22][username@eu1.ethermine.org:14444(0)][AUTHORIZE] username:username
[2022-02-08 21:54:23][FAILOVER] Switching to username@eu1.ethermine.org:14444, priority 0

does that mean something failed?

Also, when the client sets difficulty, i think it's setting an incredibly high difficulty value ( first launch gives always over  2586 s/a, that's half an hour for the first hash) is this given by the pool, or is there any "built-in" default? could it be changed, if so?

**Comment by Chainfire** [comment]
You didn't include the actual difficulty set from the logs, so I don't know if it's high or not. But 2586 s/a seems a little high, yeah. This is covered in the readme and why I advise using ViaBTC ( eth.viabtc.top:3333 ), yet everybody insists on using something else.

Difficulty is pool set. It usually doesn't adjust until after the first submit, so if your first submit takes a long time, odds are your connection will timeout before then, and you lost all your effort.

The failover line just means it selected that pool connection to use. You can supply multiple.

**Comment by tryadelion** [comment]
I missed the ViaBTC ( eth.viabtc.top:3333 ) part completely, maybe in bold / a link would be better? will switch to that. the difficulty looks like 1.000000 ( or 1,000000) on the logs, not sure what ranges can eth work on
