### ISSUE TITLE
Connected but not mining

### ISSUE THREAD

**Issue by hintro32** [Chainfire/UselethMiner#4]
I used $ADDR.$WORKER@us-east.ethash-hub.miningpoolhub.com:20535, the DAG generated and then the miner connected to the pool but it is not mining

![image](https://user-images.githubusercontent.com/81028826/149487214-abf3a10f-52f2-4468-b28b-413759820196.png)
![image](https://user-images.githubusercontent.com/81028826/149487362-d18fcadd-0179-4184-a62f-1a018f51790d.png)

This is the DAG file generated, which is smaller than I expect
![image](https://user-images.githubusercontent.com/81028826/149487634-b7e96181-0cc3-4fc6-b887-0b21b7891759.png)

**Comment by hintro32** [comment]
Is it an issue with the current epoch?

**Comment by Chainfire** [comment]
Try v0.2. This pool works for me, so that's all I can think of.

**Comment by hintro32** [comment]
Thanks! It is working better on two of my workers now (windows 10 and hive os). However, it does not work on another Linux machine in a different network (same behavior as before), but on there I am able to connect to miningpoolhub with or without ssl for GPU mining. Also the miner does not seem to work with crazypool anywhere.
