### ISSUE TITLE
OG M1 FYI

### ISSUE THREAD

**Issue by jonny7737** [Chainfire/UselethMiner#6]
Docs say:
  To enable GPU mining with Metal, add --flavor-gpu metal parameters. To disable CPU mining, add --flavor none parameters.

  This was tested on an AS M1 Max. I fully expect it to work on an M1 Pro. No idea about the original M1.

This does work on the original M1 Mini.  Seems to require fixed thread count.  crashes with dynamic thread configuration.  CPU limiting????

I bumped fan speed to 2900 RPM to keep the CPU temp below 80C.  Running 7 threads and streaming Netflix works just fine.

Well done and thank you.

**Comment by Chainfire** [comment]
Thanks for the info. Yes, if you're using Metal, you cannot use dynamic thread configuration right now.

**Comment by Chainfire** [comment]
FYI, dynamic thread configuration will be working again from next release (v0.24 or later)
