### ISSUE TITLE
Feature request: Report hashrate to the pool

### ISSUE THREAD

**Issue by La-te** [Chainfire/UselethMiner#7]
I noticed that while my other miners report the hashrate to the pool Useleth is not. That would help following the mining.
Another minor thing would be to have a possibility to display MH/s on the console output instead of h/s.

**Comment by Chainfire** [comment]
I'm not even sure what's going on here. The pool *should* show the hashrate, though it may take a while. In particular, you need some accepted submits and the pool needs to have lowered the difficulty to a number where we have a submit about once a minute or more.

Pool displayed hashrate are estimated that are only accurate on average if tracked for a long time with a stable input hashrate.

**Comment by La-te** [comment]
I'm not an expert on the topic either. However, for example Ethermine dashboard shows me reported hashrate and current hashrate for each worker. For my other miners I have both values but with Useleth miner the reported hashrate is 0 and the current hashrate is something real.

My assumption is that the reported hashrate is just a value sent by the miner and current then the actual in the pool. That reported hashrate helps tracking multiple workers from the dashboard as then you can see if the worker is itself thinking of doing it's job.

**Comment by Chainfire** [comment]
Might be that's an EthereumStratum 2.0 feature, which currently isn't supported. I'll keep an eye out in case I update that part of the tool, but that might be a while.

**Comment by lwYeo** [comment]
I'm experiencing the same thing, here is an example.
 
<img width="550" alt="Screenshot 2022-01-23 at 3 23 22 PM" src="https://user-images.githubusercontent.com/13805146/150668777-3013a6e6-88ac-4e10-b0a4-53d33ff8f43b.png">

**Comment by tryadelion** [comment]
i believe chain is correct, https://eips.ethereum.org/EIPS/eip-1571#hashrate
